# use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example' do
  pod "MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  pod "MWPhotoBrowser", :path => "../"

  pod 'XCDYouTubeKit'
end
